apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain-tasks-app
  template:
    metadata:
      labels:
        app: brain-tasks-app
    spec:
      containers:
      - name: brain-tasks-app
        image: 795974654805.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest
        ports:
        - containerPort: 3000

